spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/spring-security
    username: root
    password: 
      
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect

server:
  port: 1
